Add first 5 pages' content of chapter 6
dmst-sweng/swebok-el pull request #53
Opened 2023-04-15 19:08 UTC by TeoSkondras

Software engineering operations Chapter

2023-04-15 23:11 UTC, dspinellis requested changes
Well done!  I like the language and your attention to detail. I made a few small comments for minor improvements following a quick scan.

Also, nice commit message. Many get this wrong.

2023-04-15 23:11 UTC, dspinellis commented on manuscript/6-SoftEngOps.txt
> +Στο IEEE 12207 [3], ένας χειριστής (operator) ορίζεται ως "άτομο ή οργανισμός που εκτελεί τις
πρότυπο IEEEE … [παντού]

2023-04-15 23:11 UTC, dspinellis commented on manuscript/6-SoftEngOps.txt
> +### Scripting και αυτοματοποίηση
Εκτέλεση σεναρίων και …

2023-04-18 12:24 UTC, TeoSkondras commented
Committed a new version fixing those issues!

2023-04-21 10:12 UTC, TeoSkondras commented
Must do, Italics and Bold + για νέο κεφάλαιο όχι κάθε λέξη να αρχιζει με κεφαλαίο.

2023-04-23 11:22 UTC, athakaras commented on manuscript/6-SoftEngOps.txt
> +|MR     |Modification request               |
one acronym missing (KPI)

2023-04-23 11:23 UTC, athakaras commented on manuscript/6-SoftEngOps.txt
> +Οι λειτουργίες μηχανικής λογισμικού αναφέρονται στο σύνολο των δραστηριοτήτων και
* λειτουργίες μηχανικής λογισμικού * --> use italics

2023-04-23 11:26 UTC, athakaras commented on manuscript/6-SoftEngOps.txt
> +και δημοσιεύονται στο Ινστιτούτο Ηλεκτρολόγων και Ηλεκτρονικών Μηχανικών (IEEE) 20000 [1].
στο πρότυπο 20000 του Ινστιτούτου ....

2023-04-23 11:32 UTC, athakaras commented
@TeoSkondras very good work and attention to detail

as you have mentioned, you must use italics and bold in every word that requires so from the english version

2023-05-05 14:48 UTC, merged